import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Emazon Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1 className="text-4xl text-center font-bold">Welcome to our website!</h1>
      </main>
    </>
  );
}
